### ISSUE TITLE
Docs update: Include reference to the Docker image

### ISSUE THREAD

**Issue by lirantal** [lirantal/pie-my-vulns#35]
We have a docker image now in Docker Hub (https://hub.docker.com/r/lirantal/pie-my-vulns) thanks @omeraha (thank you Omer! ❤️).

How about we update the README with instructions on using it?
Omer, would be great if you also wanted to run some tests on the image to make sure everything works ok. Every merge to master will trigger the dockerfile rebuild.

**Comment by omeraha** [comment]
Sure! Would be glad to do that!

**Comment by lirantal** [comment]
Thanks

**Comment by omeraha** [comment]
@lirantal I will add the tests as part of this issue: https://github.com/lirantal/pie-my-vulns/issues/52, so I can easily pass the authentication key to the docker container (so it does not block the CI pipeline).
