### ISSUE TITLE
Feat: enable the CLI to receive Snyk's JSON input from stdin

### ISSUE THREAD

**Issue by lirantal** [lirantal/pie-my-vulns#5]
## Description

In essence, `pie-my-vulns` uses the Snyk CLI behind the scenes to scan and use the JSON output of that to chart the vulnerabilities. If someone has the Snyk CLI already installed, they could do something like `snyk test --json | npx pie-my-vulns`. To enable that we should support getting the JSON input from stdin and also when that takes place there's no need to run the audit within `pie-my-vulns`'s own code.

**Comment by DrFaust92** [comment]
Ill take a crack at this
