### ISSUE TITLE
"Scanning project dependencies" appears twice when authentication is required

### ISSUE THREAD

**Issue by omeraha** [lirantal/pie-my-vulns#51]
## Expected Behavior

The output "Scanning project dependencies" should appear only once.

## Current Behavior

"Scanning project dependencies" appears twice if authentication against Snyk is required. It should appear only once. This is happening since when the user is not authenticated, an error is being thrown and after a successful authentication, the same code (that issues the message) is invoked again.

![image](https://user-images.githubusercontent.com/43315856/77829193-8fe97780-7131-11ea-89bb-ee23a6263875.png)

## Possible Solution

Check authentication before starting the actual test. If this is not possible, a flag can be added to prevent the double printing 

## Steps to Reproduce (for bugs)

1. Run pie-my-vulns unauthenticated
2. Inspect command output

## Your Environment

- Library Version used:
- Node.js version (e.g. Node.js 5.4): 12.16.1
- Operating System and version (desktop or mobile): mac OS

**Comment by omeraha** [comment]
@lirantal from looking at the output of `snyk/dist/cli/index.js --help `, is seems like there's no way to check if a user is authenticated. What do you think about calling [authenticate()](https://github.com/lirantal/pie-my-vulns/blob/master/src/Audit.js#L23) as part of the regular flow, and not only if the [test()](https://github.com/lirantal/pie-my-vulns/blob/master/src/Audit.js#L48) method throws an error?

**Comment by lirantal** [comment]
Good point. Hmmm, how about we add another method, something like `runAudit()` that will then just call both of them one after the other. Will that work? I like having these two as separate functions that we can test and call on their own.

also cc'ing @dkorn who might have had similar thoughts to yours when working on it.
