### ISSUE TITLE
--directory argument ignored if not authenticated against snyk service

### ISSUE THREAD

**Issue by omeraha** [lirantal/pie-my-vulns#57]
If not authenticated agains the Snyk service, the --directory cli argument is ignored, and the current directory is being tested. After a successful authentication the command works as expected.
## Expected Behavior

The directory passed to the --directory cli argument should be tested
## Current Behavior

The current directory is tested, and --directory is ignored.
## Possible Solution

Requires further investigation
## Steps to Reproduce (for bugs)

1. Remove authentication key (run `snyk config unset api   `)
2. Run pie-my-vulns with the directory arg (i.e. `npx pie-my-vulns --directory='path'`. Make sure the flag point to a directory other than the current one.
3. Verify the command output is the same as it would be if the command was ran on the current directory

## Your Environment

- Library Version used:
- Node.js version: v12.16.1
- Operating System and version (desktop or mobile): macOS

**Comment by lirantal** [comment]
@omeraha thanks for opening. are you going to send in a PR to fix it? :-)

**Comment by omeraha** [comment]
Sure. Just give me a couple of minutes. Was a simple bug, testing the fix now.
