### ISSUE TITLE
Fix NaN and no display when no vulnerabilities are found

### ISSUE THREAD

**Issue by lirantal** [lirantal/pie-my-vulns#8]
## Expected Behavior

When no vulnerabilities are found the CLI should say so or if in JSON output mode should just end with exit code 0.

## Current Behavior

See what happens:
![image](https://user-images.githubusercontent.com/316371/74106491-23f68400-4b70-11ea-9bed-765d2a9c9213.png)

## Steps to Reproduce (for bugs)

1. Be in a project with no vulnerabilities (i.e: npm init --yes also works)
2. `npx pie-my-vulns`
3. Observe issue like screenshot above

**Comment by omeraha** [comment]
I'd be glad to take this one!

**Comment by omeraha** [comment]
Is this ok (fixed only one of the reporters for now)?
![image](https://user-images.githubusercontent.com/43315856/75550928-a66db780-5a3b-11ea-8dfb-8f3b09030534.png)

**Comment by lirantal** [comment]
Nice progress!
I guess I'm wondering what do you think should be the best output?

If there are no vulnerabilities at all, then the rest of the charts have no meaning either and will always show 0.

Should we maybe just exist by saying 0 vulnerabilities found and that's it?

**Comment by omeraha** [comment]
Agree.

**Comment by lirantal** [comment]
I'm good with whatever you come up with, so waiting for the PR :-)

**Comment by rajkumaar23** [comment]
@lirantal Looks like this is fixed by #24

**Comment by lirantal** [comment]
Indeed, thanks!
